# Generated by Django 5.2 on 2026-07-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('plan', models.CharField(default='free', max_length=50)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_score', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tenant_id', 'email')},
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('action_taken', 'Action Taken'), ('risk_flag', 'Risk Flag'), ('opportunity', 'Opportunity'), ('general', 'General')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_agent', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student')),
            ],
        ),
    ]
