# Generated by Django 5.2 on 2026-07-10 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCPApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('key_prefix', models.CharField(db_index=True, max_length=8)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('capabilities', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('requests_per_minute', models.IntegerField(default=60)),
                ('requests_per_day', models.IntegerField(default=10000)),
                ('agent_description', models.TextField(blank=True)),
                ('allowed_tools', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('last_used_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'mcp_api_key',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'key_prefix'], name='mcp_api_key_tenant__bdd477_idx')],
            },
        ),
        migrations.CreateModel(
            name='MCPApiKeyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('denied', 'Permission Denied'), ('rate_limit', 'Rate Limited'), ('timeout', 'Timeout')], max_length=20)),
                ('tenant_id', models.IntegerField(db_index=True)),
                ('tool_name', models.CharField(db_index=True, max_length=100)),
                ('arguments', models.JSONField()),
                ('result_rows', models.IntegerField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(null=True)),
                ('invoked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('agent_version', models.CharField(blank=True, max_length=50)),
                ('request_count', models.IntegerField(default=0)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='mcp_server.mcpapikey')),
            ],
            options={
                'db_table': 'mcp_api_key_usage',
                'ordering': ['-invoked_at'],
                'indexes': [models.Index(fields=['api_key', 'invoked_at'], name='mcp_api_key_api_key_239f94_idx'), models.Index(fields=['tenant_id', 'invoked_at'], name='mcp_api_key_tenant__470dc5_idx')],
            },
        ),
    ]
