# Generated by Django 5.2 on 2026-07-10 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('api_calls', models.IntegerField(default=0)),
                ('daily_active_users', models.IntegerField(default=0)),
                ('feature_slug', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['student', 'recorded_at'], name='analytics_u_student_845901_idx')],
            },
        ),
    ]
